apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lambda
  name: lambda
  namespace: lambda
  # argotrigger: blah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda
  strategy: {}
  template:
    metadata:
      labels:
        app: lambda
      namespace: lambda
    spec:
      containers:
      - image: gwright99/lambda_py3.11:base
        name: lambda-py3-11
        # command: ["sleep", "300"]
        ports:
        - containerPort: 8080
        env:
          - name: CR_USER
            valueFrom:
              secretKeyRef:
                name: gh-pat
                key: cr_user
          - name: CR_PAT
            valueFrom:
              secretKeyRef:
                name: gh-pat
                key: cr_pat

      - image: nginx:latest
        name: mynginx
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: nginx-message
            mountPath: /usr/share/nginx/html/
      
      # https://pwittrock.github.io/docs/tasks/configure-pod-container/configure-pod-configmap/
      volumes:
        - name: nginx-message
          configMap:
            name: nginx-message
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-message
  namespace: lambda
data:
  index.html: |
    <html>
    <h1>Please use POST methods to call the Lambda function</h1>
    </br>
    <p>You tried to call this Lambda function with an HTTP GET method (likely from your browser).
    The Lambda handler expects requests to be sent as HTTP POST. Please try again.</p>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lambda
  name: lambda
  namespace: lambda
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lambda
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lambda
  name: lambda-mynginx
  namespace: lambda
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: lambda
status:
  loadBalancer: {}
---
# Cheating -- to handle GETS to Lambda (which only handles POSTS) just redirect to nginx.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    example: lambda
  name: lambda
  namespace: lambda
spec:
  hostnames:
  - lambda.grahamwrightk8s.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: public-cloudflare
    namespace: gloo-system
  rules:
    # Redirect Lambda to NGINX warning to use Post
    - matches:
      - method: "GET"
      backendRefs:
        - name: lambda-mynginx
          kind: Service
          group: ""
          port: 8000
          #weight: 1

    # Actual code
    - matches:
      # - method: "POST"
      - path:                 # <--- new start. Works when method: POST not active
          type: PathPrefix 
          value: "/test"
        method: POST
      
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/2015-03-31/functions/function/invocations"

      backendRefs:
        - name: lambda
          kind: Service
          group: ""
          port: 8080
          #weight: 1