---
# Originally had ArgoCD Hook above. Is fact that CM doesn't yet exist causing problem?
apiVersion: v1
kind: ConfigMap
metadata:
  name: app4-purgescript
  namespace: lambda
data:
  purge.sh: |
    # Not getting created why?
    apt update && apt install -y jq

    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt

    sleep 5
    jq --version

    CONTAINERNAME=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/$NAMESPACE/pods | jq '.items[].metadata.name' | echo $(grep app4) | xargs)
    sleep 5
    echo $CONTAINERNAME
    curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/api/v1/namespaces/$NAMESPACE/pods/$CONTAINERNAME
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: delete-fourth-application
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: lambda
spec:
  template:
    spec:
      serviceAccountName: deletelambda
      containers:
      - name: delete-fourth-app      # Can't call it `app4-delete` cuz app4 gets picked up by the unsophistocated grep
        image: nginx:latest
        command: ["/bin/bash"]
        args: ["-c", "/tmp/purge/purge.sh"]
        volumeMounts:
          - name: app4-purgescript
            mountPath: /tmp/purge/
      volumes:
        - name: app4-purgescript
          configMap:
            defaultMode: 0777   # To defeat ReadOnly
            name: app4-purgescript
            items:
              - key: purge.sh
                path: purge.sh
      restartPolicy: Never